var k={c:null,F:null,w:null,l:null,i:null,f:null,g:null,result:!0,x:null,y:null,A:null,j:null,o:1,s:1,u:0,I:function(a){var b=this;a&&(this.c=$(".innerBox").get(0),this.F=$(".headerWrapper").get(0),this.w=$(".myDetails"),this.i=$(".resultDisplayer"),this.g=$(".rhs"),this.f=$(".lhs"),this.l=$(".componentButton.equals"),this.D=$(".buildUp"),this.K(),window.console.log=function(a,e){b.R(a,e)});clearInterval(this.u);this.u=setInterval(this.M.bind(this),20)},K:function(){var a=this;$(a.c).Y(function(){clearInterval(a.u);
$(this).J("animate").B("stopped");a.w.finish().T("fast")},function(){a.I();$(this).J("stopped").B("animate");a.w.finish().ba("fast")}).click(function(){window.open("https://www.facebook.com/profile.php?id=100007985747854","_blank")});a.i.aa("click",".reference",function(){window.open("http://www.ecma-international.org/ecma-262/5.1/#sec-11.9.3","_blank")});a.f.add(a.g).$(function(b){13==b.keyCode&&a.l.click()});a.D.click(function(){window.localStorage.setItem("buildUp",1);$(this).X("fast",function(){$(this).remove()})});
a.l.click(function(){var b=a.f.V().trim(),d=a.g.V().trim(),e,g;if(0==b.length||0==d.length)a.f.add(a.g).L("borderBottomColor","rgba(54, 88, 153, 0.1)").data("reset","0"),clearTimeout(a.timeout),a.C(0==b.length?a.f:a.g);else try{a.S(),a.result=eval("("+b+") == ("+d+")"),e=eval("("+b+")"),g=eval("("+d+")"),a.h(e,g,1,"object"==typeof e&&null!==e?a.m(e):b,"object"==typeof g&&null!==g?a.m(g):d),console.log("RESULT : "+a.result.toString().toUpperCase(),a.result.toString())}catch(h){console.log("&#x26D4; "+
h,"error")}});$(window).resize(function(){a.A=a.F.getBoundingClientRect()}).resize().load(function(){setTimeout(function(){$("#disqus_thread").B("discussPartialDisplay");null==window.localStorage.getItem("buildUp")&&a.D.T("slow")},2E3)})},M:function(){this.j=window.getComputedStyle(this.c);this.x=parseInt(this.j.left);this.y=parseInt(this.j.top);if(0>this.x||this.x+20>this.A.width)this.o=-this.o;if(0>this.y||this.y+20>this.A.height)this.s=-this.s;this.c.style.left=this.x+this.o+"px";this.c.style.top=
this.y+this.s+"px"},C:function(a,b){b=void 0===b?1:b;var d=this;this.timeout=setTimeout(function(e){e=+a.data("reset");a.L("borderBottomColor",0==e?"rgb(255, 0, 0)":"rgba(54, 88, 153, 0.1)");a.data("reset",+!e);6!=b&&d.C(a,++b)},200)},S:function(){this.i.empty().J("center")},R:function(a,b){return $("<p class="+b+">").Z(("explanation"==b?"&#x21E8; ":"")+a).W(this.i)},b:function(a){return"string"==typeof a?'"'+a+'"':"object"==typeof a?this.m(a):a},G:function(a,b){return"boolean"==b?+a:a},H:function(a,
b,d){return a=b==d?this.U(a):a},U:function(a,b){b=typeof a.valueOf();return"object"===b?a.valueOf().toString():a.valueOf()},m:function(a){return Object.prototype.toString.call(a).includes("Array")?"[...]":"{Object...}"},v:function(a,b){return"undefined"===a||"object"===a&&null===b},O:function(a,b,d,e){return"number"==a&&"object"==b&&null!=e||"object"==a&&null!=d&&"number"==b||"string"==a&&"object"==b&&null!=e||"object"==a&&null!=d&&"string"==b},N:function(a,b){return"number"===a&&"string"===b||"string"===
a&&"number"===b},P:function(a,b){return"boolean"===a||"boolean"===b},a:function(a,b){switch(a){case 1E3:console.log("Refer line numbers 1.A and B in AECA.","reference");break;case 1001:console.log("Refer line numbers 1.C.i and ii in AECA.","reference");break;case 1002:switch(b){case "number":console.log("Refer line numbers 1.C.iii ,iv ,v and vi in AECA.","reference");break;case "string":console.log("Refer line number 1.D in AECA.","reference");break;case "boolean":console.log("Refer line number 1.E in AECA.",
"reference");break;case "object":console.log("Refer line number 1.F in AECA.","reference")}break;case 1003:console.log("Refer line number 2 and 3 in AECA.","reference");break;case 1004:console.log("Refer line number 4 and 5 in AECA.","reference");break;case 1005:console.log("Refer line number 6 and 7 in AECA.","reference");break;case 1006:console.log("Refer line number 8 and 9 in AECA.","reference");break;case 1007:console.log("Refer line number 10 in AECA.","reference")}},h:function(a,b,d,e,g,h){var c=
typeof a,f=typeof b;c==("function"==c)?"object":c;f==("function"==f)?"object":f;console.log("CALL #"+d+"<span>Arguments - LHS : "+e+" RHS : "+g+"</span>","steps");if(c===f)this.v(c,a)?(console.log("Both LHS and RHS are '"+(a+"")+"'. Hence the given expression will always be evaluated to 'true'.","explanation"),this.a(1E3)):"number"!==c||a===a&&b===b?(console.log("LHS and RHS are of same type '"+c+"'. Additionally, both are having "+(a===b?"same":"different")+("object"===c?" References":" values")+
". So the given expression will be evaluated to '"+(a===b).toString()+"'.","explanation"),this.a(1002,c)):(console.log("Though LHS and RHS are of type number, "+(a!==a?"LHS":"RHS")+" is 'NaN'. Basically 'NaN' will be evaluated to false even it is compared with itself. So the given expression will yield 'false' always.","explanation"),this.a(1001));else if(this.v(c,a)&&this.v(f,b))console.log("When 'undefined' and 'null' are compared the result will always be 'true'. In our case LHS resolves to '"+
(a+"")+"' and RHS resolves to '"+(b+"")+"'. So the given expression will evalautes to 'true'","explanation"),this.a(1003);else{if(this.N(c,f))return console.log("LHS is a '"+c+"' and RHS is a '"+f+"', Hence "+("string"===c?"LHS":"RHS")+" will be converted to 'number' first.","explanation"),console.log(("string"===c?"LHS":"RHS")+" will be converted as number to form the expression ("+(a=+a,a)+" == "+(b=+b,b)+"). After that, algorithm will be called recursively by supplying the gained expression.",
"explanation"),this.a(1004),this.h(a,b,++d,a,b);if(this.P(c,f))return console.log("If either RHS or LHS is a boolean, then it has to be converted to number first.","explanation"),console.log("Here, "+("boolean"==c?"LHS":"RHS")+" is boolean. So after translating it into a number the whole expression becomes like below,","explanation"),a=this.G(a,c),b=this.G(b,f),console.log(this.b(a)+" == "+this.b(b)+". And here we need a recursive call to the algorithm, to evaluate the newly generated expression.",
"explanation"),this.a(1005),this.h(a,b,++d,this.b(a),this.b(b));if(this.O(c,f,a,b))return h="object"===c?"RHS":"LHS",console.log(h+" is a "+("object"===c?f:c)+". And its opponent is an object. So object has to be converted to its primitive form first before further evaluations.","explanation"),console.log("ToPrimitve("+("RHS"==h?"LHS":"RHS")+") will be called and the following expression will be framed,","explanation"),a=this.H(a,h,"RHS"),b=this.H(b,h,"LHS"),console.log(this.b(a)+" == "+this.b(b)+
". Next, the framed expression will be passed to a recursive call of the algorithm.","explanation"),this.a(1006),this.h(a,b,++d,this.b(a),this.b(b));console.log("No condition match found in AECA! Hence the given expression will be evaluated as 'false'","explanation");this.a(1007)}}};$(k.I.bind(k,!0));